Update encounter_rewards.csv
naw-db/naw-db.github.io pull request #70
Opened 2023-05-04 11:27 UTC by MitchPleaseAllWorld

2023-05-04 14:09 UTC, unkdrew requested changes

2023-05-04 14:09 UTC, unkdrew commented on content/data/players.csv
> -Bojan Bogdanovic,B. Bogdanovic,1,1,4,Starter,DET,Central,East,SF,PF,14,17,14,14,12,8,10,11,13,16,71,87,70,72,58,42,48,55,64,80,Larry Nance Jr.,Dillon Brooks,Lonzo Ball,,
Should be `Jr.`, not `Jr`

2023-05-04 14:09 UTC, unkdrew commented on content/data/players.csv
> +Dillon Brooks,D. Brooks,1,1,4,Starter,MEM,SouthWest,West,SF,SG,14,14,15,12,14,9,12,12,13,16,70,72,77,61,70,46,58,58,64,80,TJ McConnell,Alec Burks,Pascal Siakam,,
Should be `Southeast`, not `SouthEast`. Same with Southwest.

2023-05-04 14:09 UTC, unkdrew commented on content/data/players.csv
> +CJ Mccollum,C. McCollum,4,2,5,All-Star,NOP,SouthWest,West,SG,PG,26.9,23.8,29.9,20.8,17.7,19.1,18.7,18.9,23.8,27,89,80,98,71,62,66,63,64,80,90,,Kevin Love,?,?,
Should be McCollum

2023-05-05 09:21 UTC, MitchPleaseAllWorld commented on content/data/players.csv
> +CJ Mccollum,C. McCollum,4,2,5,All-Star,NOP,SouthWest,West,SG,PG,26.9,23.8,29.9,20.8,17.7,19.1,18.7,18.9,23.8,27,89,80,98,71,62,66,63,64,80,90,,Kevin Love,?,?,
strange, I thought I changed all those things. I'll fix it again

2023-05-05 16:13 UTC, unkdrew commented on content/data/players.csv
> +CJ Mccollum,C. McCollum,4,2,5,All-Star,NOP,SouthWest,West,SG,PG,26.9,23.8,29.9,20.8,17.7,19.1,18.7,18.9,23.8,27,89,80,98,71,62,66,63,64,80,90,,Kevin Love,?,?,
Just changed all NorthWest to Northwest, seems to be a miss :)

2023-05-05 16:14 UTC, unkdrew approved these changes

2023-05-05 16:25 UTC, merged